### ISSUE TITLE
Firefox Extension

### ISSUE THREAD

**Issue by colinkautz** [ronanru/uploadthing-darkmode#1]
Hi! Big fan of your chrome extension, but I'm one of those weirdos who uses Firefox as their main browser. Could you port this to Firefox?

**Comment by matrv** [comment]
It works on firefox if you change the manifest version to 2. I submitted it to the firefox addons store. I will do a bit more testing and add a firefox release tomorrow.

**Comment by matrv** [comment]
Mozilla has approved the addon, I added the link to it to the readme
